[package]
name = "hanzo-flash-attn-v3"
version = "0.10.2"
edition = "2021"

description = "Flash attention v3 layer for the hanzo ML framework."
repository = "https://github.com/huggingface/hanzo"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT OR Apache-2.0"
readme = "README.md"
exclude = ["cutlass/docs/**", "cutlass/test/**", "cutlass/examples/**", "cutlass/tools/**", "cutlass/media/**"]

[dependencies]
hanzo = { path = "../hanzo-core", features = ["cuda"], package = "hanzo-core", version = "0.10.2" }
half = { version = "2.3.1", features = ["num-traits"] }

[build-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
num_cpus = "1.15.0"
rayon = "1.7.0"
cudaforge = "0.1"

[dev-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
hanzo-nn = { path = "../hanzo-nn", features = ["cuda"] }
rstest = "0.23"
